### ISSUE TITLE
It is prohibited to sell the material.

### ISSUE THREAD

**Issue by malaterre** [libjxl/testdata#1]
[Thanks for splitting testdata from libjxl]

The main page should make it a bit more clear that imagecompression.info/* files are a bit more restrictive than the top-level BSD style license.

> it must be available freely under the conditions stated here. That is, it is prohibited to sell the material.

* https://github.com/libjxl/testdata/blob/main/third_party/imagecompression.info/LICENSE.txt

**Comment by malaterre** [comment]
I see a single solution for my issue: Upload a stripped version of testdata to Debian archive. I'll remove the subfolder `imagecompression.info`. This means I'll need to remove a portion of the libjxl test suite. Hopefully there is nothing really particular with these images.

cc: @jonsneyers

**Comment by mo271** [comment]
Thanks for bringing this up!
We are working on not depending on imagecompression.info anymore.

**Comment by mo271** [comment]
#2 prepares the move away from using any data from `imagecompression.info`. Leaving this open until we have updated the commit hash of the submodule `testdata` in `libjxl/libjxl` and adapted the corresponding tests.
